pipeline {
    agent { label 'agent' }

    environment {
        // 환경 변수 설정
        ECR_REPO = '211125697339.dkr.ecr.ap-northeast-2.amazonaws.com/mute-backend' 
        SSH_CREDENTIALS_ID = 'ec2_ssh_key'
    }

    stages {
        stage('Deploy to EC2') {
            steps {
                withCredentials([string(credentialsId: 'ec2_ssh_backend', variable: 'EC2_INSTANCE_IP')]) {
                    script {
                        // SSH를 통해 EC2에 연결하고, ECR 이미지를 가져와 실행
                        sshagent([SSH_CREDENTIALS_ID]) {
                            sh """
                            ssh -o StrictHostKeyChecking=no ec2-user@${EC2_INSTANCE_IP} '
                            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${ECR_REPO}
                            docker stop back-server || true
                            docker rm back-server || true
                            docker run -d --name back-server -p 3000:3000 ${ECR_REPO}:${IMAGE_TAG}
                            docker system prune -f 
                            docker image prune -f
                            '
                            """
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Deployment process completed.'
            // 배포 후 정리 작업이나 상태 확인 등의 추가적인 작업을 수행할 수 있습니다.
        }
    }
}